spring:
  application:
    name: notification-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=notification
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification

  config:
    import: optional:file:.env

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

slack:
  bot-token: ${SLACK_BOT_TOKEN}

gemini:
  api-key: ${GEMINI_API_KEY}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent