FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /workspace
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY discovery-server discovery-server
RUN ./gradlew :discovery-server:bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /workspace/discovery-server/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
