spring:
  application:
    name: companyservice

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:shipflow}?currentSchema=company
    username: ${POSTGRES_USER:shipflow}
    password: ${POSTGRES_PASSWORD:1234}

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: company
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}