spring:
  application:
    name: userservice

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shipflow}?currentSchema={schema}
    username: ${DB_USER:shipflow}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: users
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/shipflow

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

keycloak:
  server-url: http://keycloak:8080
  realm: ${KEYCLOAK_REALM}
  user-realm: ${KEYCLOAK_REALM_USER}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  login-client-id: ${KEYCLOAK_LOGIN_CLIENT_ID}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
