spring:
  application:
    name: product-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=product
    username: ${DB_USER:shipflow}
    password: ${DB_PASSWORD:1234}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-wait: -1
          max-idle: 8
          min-idle: 0

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: product
    show-sql: true

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    com.shipflow.product.infrastructure.client: BASIC
    org.hibernate.orm.jdbc.bind: TRACE