name: Docker Compose Build Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

      KEYCLOAK_DB_PASSWORD: ${{ secrets.KEYCLOAK_DB_PASSWORD }}
      KEYCLOAK_ADMIN_USERNAME: ${{ secrets.KEYCLOAK_ADMIN_USERNAME }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      KEYCLOAK_REALM_USER: ${{ secrets.KEYCLOAK_REALM_USER }}
      KEYCLOAK_ADMIN_CLIENT_ID: ${{ secrets.KEYCLOAK_ADMIN_CLIENT_ID }}
      KEYCLOAK_LOGIN_CLIENT_ID: ${{ secrets.KEYCLOAK_LOGIN_CLIENT_ID }}

      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker compose up -d --build --wait --wait-timeout 500
        timeout-minutes: 25

      - name: Tear down
        if: always()
        run: docker compose down -v
